# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Flow' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Starscream', '~> 1.0.0'
    pod 'Alamofire', '~> 3.0'
end

target 'FlowTests' do

end

target 'FlowUITests' do

end

